### ISSUE TITLE
安卓版本的 回调事件都无法使用

### ISSUE THREAD

**Issue by XcXerxes** [bang88/react-native-svga-player#3]
在 安卓版本中 onFinished， onFrame，onPercentage 回调事件都无法正常监听，

**Comment by student9128** [comment]
> 在 安卓版本中 onFinished， onFrame，onPercentage 回调事件都无法正常监听，

他这个集成的有问题，现在的React Native集成原生控件不是这么搞的

**Comment by liubi520** [comment]
安卓不显示，有人遇到吗
