### ISSUE TITLE
Please upgrade its new version it will threw on upon another error when installing with react-native :0.70.3

### ISSUE THREAD

**Issue by ardhendu12345** [bang88/react-native-svga-player#31]
Please upgrade its new Version , it gets deprecated for react-native Version:0.70.3...Please upgrade it ..

**Comment by ardhendu12345** [comment]
Hey Please upgrade for new react-native version ...Please...

**Comment by iasreact1** [comment]
@bang88  please help ...when installed its builed failed ..please upgrade it

**Comment by BANG88** [comment]
please file a PR directly.

**Comment by iasreact1** [comment]
@bang88  Can you explain me what to do ? not understand

**Comment by iasreact1** [comment]
@bang88  first issue
* Where:
Build file '/Users/username/Documents/New Projects/Project_name/node_modules/react-native-svga-player/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-svga-player'.
> Plugin with id 'maven' not found.

**Comment by iasreact1** [comment]
@bang88  after solving some issues at last the error comes which got no solution
A problem occurred configuring project ':react-native-svga-player'.
> Could not find method mavenDeployer() for arguments [build_1vgpslp8jdh77190hqiajl56s$_run_closure4$_closure16$_closure18@75d11edf] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.
Please help sir...

**Comment by BANG88** [comment]
@xiongxiongDream Will working on it.

**Comment by iasreact1** [comment]
No its build will failed getting one upon another error please help sir @xiongxiongDream , ok sir can i know how much time it will take ?

**Comment by xiongxiongDream** [comment]
> 不，它的构建将失败，出现一个接一个的错误，请帮助先生@xiongxiongDream，好的先生，我可以知道需要多少时间吗？

you can do like this in root build.gradle file as follows: 

allprojects {
    repositories {
+       exclusiveContent {
+           // We get React Native's Android binaries exclusively through npm,
+           // from a local Maven repo inside node_modules/react-native/.
+           // (The use of exclusiveContent prevents looking elsewhere like Maven Central
+           // and potentially getting a wrong version.)
+           filter {
+               includeGroup "com.facebook.react"
+           }
+           forRepository {
+               maven {
+                   // NOTE: if you are in a monorepo, you may have "$rootDir/../../../node_modules/react-native/android"
+                   url "$rootDir/../node_modules/react-native/android"
+               }
+           }
+       }
        // ...
    }
}

 this is the easiest way to build project successfully

**Comment by xiongxiongDream** [comment]
@iasreact1  Two methods are provided to solve this problem. See the latest code for the second

**Comment by iasreact1** [comment]
`allprojects {
    repositories {
        exclusiveContent {
      // We get React Native's Android binaries exclusively through npm,
      // from a local Maven repo inside node_modules/react-native/.
      // (The use of exclusiveContent prevents looking elsewhere like Maven Central
      // and potentially getting a wrong version.)
      filter {
          includeGroup "com.facebook.react"
      }
      forRepository {
          maven {
              // NOTE: if you are in a monorepo, you may have "$rootDir/../../../node_modules/react-native/android"
              url "$rootDir/../node_modules/react-native/android"
          }
      }
     }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
    }
    
}`
@xiongxiongDream  my project_name/android/build.gradle look like this Now but generate same error...No problem get Fixed, please  help with proper solution..

**Comment by iasreact1** [comment]
@xiongxiongDream please check properly , i changed my files according to your changes but same error come ..plugin id 'maven' not found .. Sir, can u please guide me to play svga animation in any project..please help sir..

**Comment by iasreact1** [comment]
@bang88  @xiongxiongDream  how can we use local .svga files to play svga animation ? or i have to always use url here??

**Comment by xiongxiongDream** [comment]
> @xiongxiongDream please check properly , i changed my files according to your changes but same error come ..plugin id 'maven' not found .. Sir, can u please guide me to play svga animation in any project..please help sir..

if you use the Gradle 7.x, the maven plugin has been removed, you need use  the maven-publish plugin instead, svga pr you can go to https://github.com/svga/SVGAPlayer-Android look for usage
