### ISSUE TITLE
Build failed on Ios after runing npx react-native-run-ios

### ISSUE THREAD

**Issue by iasreact1** [bang88/react-native-svga-player#42]
i have used 
react-native -> 0.73.1
react-native-svga-player ->1.1.0

When use 
pod install ->successfully installed
when build the project using
npx react-native-run-ios

build failed command
`The following build commands failed:
        CompileC /Users/userName/Library/Developer/Xcode/DerivedData/AwesomeProjects-bicxyrclsyxmypclupddbdsppuxa/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SVGAPlayer.build/Objects-normal/x86_64/Svga.pbobjc.o /Users/userName/Documents/DemoProjectFolde/AwesomeProjects/ios/Pods/SVGAPlayer/Source/pbobjc/Svga.pbobjc.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'SVGAPlayer' from project 'Pods')
(1 failure)`

please help @BANG88 @xiongxiongDream

**Comment by iasreact1** [comment]
![svgaBug](https://github.com/BANG88/react-native-svga-player/assets/118831987/54d9026e-7424-4966-bc39-eee7206e50c9)
Please check it @BANG88  @xiongxiongDream

**Comment by BANG88** [comment]
Please  use lottie or other solution instead.

**Comment by iasreact1** [comment]
Please @BANG88  i have no option for showing svga animation, Please update it...
i have to show .svga file, no way to use lottie nor any other solution for .svga file 
Please help @BANG88

**Comment by iasreact1** [comment]
@BANG88 @xiongxiongDream  Please help me Sir, ... i haven't found anything else....Please help to solve it

**Comment by BANG88** [comment]
@iasreact1 Can you provide a simple reproduction, like a git repo, so I can run it quickly to see the specific issue? thanks.

**Comment by iasreact1** [comment]
@BANG88  [https://github.com/iasreact1/DemoRnt.git](url)
Please run this project ...Thanks for replying...please help sir 
Thanks in advance

**Comment by iasreact1** [comment]
@BANG88 @xiongxiongDream Hello sir , any update sir ? regarding the issue...please help sir

**Comment by iasreact1** [comment]
@BANG88 Please check the repo sir ....

**Comment by BANG88** [comment]
@iasreact1 Sorry for replying so late, I've been sick these past few days.You need to manually modify the file by adding this include at the beginning of the file. There's an issue with iOS dependencies, but no one is maintaining it anymore. You can add it in your local file.


`#include <libkern/OSAtomic.h>`


<img width="1272" alt="image" src="https://github.com/BANG88/react-native-svga-player/assets/433259/85a9921a-371c-4cb9-9f73-21b078e596db">


Open the iOS directory with Xcode, then navigate to the file location shown in the above image for modification.

**Comment by iasreact1** [comment]
@BANG88 will it solve the build failed in ios & i can play svga animation in ios ?

**Comment by BANG88** [comment]
‌‌‌You can try according to what was mentioned above. I was able to successfully run your demo, which means there are no issues with the Build now.

**Comment by iasreact1** [comment]
@BANG88  Thank you sir For the above solution.. this above error will remove but at the last stage of build it will come that error please help to remove sir ..Thanks in advance
"'React/RCTThirdPartyFabricComponentsProvider.h' file not found" at RCTFabricComponentsPlugins 
![WhatsApp Image 2024-03-13 at 7 55 39 PM](https://github.com/BANG88/react-native-svga-player/assets/118831987/cc0d26f7-fcc0-4ced-b1c7-bba80955ba8e)

**Comment by iasreact1** [comment]
![Uploading WhatsApp Image 2024-03-13 at 7.55.39 PM.jpeg…]()

**Comment by iasreact1** [comment]
I again pod install and it will solve my issue thanks @BANG88
